'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const a=html.indexOf('const PC_DND_STRUCTURE_LAYOUTS=Object.freeze({'),b=html.indexOf('async function pcDndStructurePreviewFile(',a);
assert.ok(a>=0&&b>a);
const cell=(sheet,ref)=>{const m=/^([A-Z]+)(\d+)$/.exec(ref);let col=0;for(const c of m[1])col=col*26+c.charCodeAt(0)-64;return sheet?.rows?.[+m[2]-1]?.[col-1]??'';};
const api=new Function('pcInsaneSheetCell',html.slice(a,b)+'return {read:pcDndStructurePreviewFromSheets,render:pcDndStructurePreviewHTML,profiles:PC_DND_STRUCTURE_LAYOUTS,anchors:PC_DND_SOURCE_ANCHORS,match:pcDndAbilityLabelMatches};')(cell);
const labels=['力量','敏捷','体质','智力','感知','魅力'];
function put(rows,ref,value){const m=/^([A-Z]+)(\d+)$/.exec(ref);let col=0;for(const c of m[1])col=col*26+c.charCodeAt(0)-64;(rows[+m[2]-1]??=[])[col-1]=value;}
function fixture(id){const p=api.profiles[id],wb=Array.from({length:p.sheetCount},()=>({name:'PRIVATE_SHEET_SHOULD_NOT_RENDER',rows:[]}));p.refs.forEach((ref,i)=>put(wb[1].rows,ref,labels[i]));p.candidateRefs.forEach((ref,i)=>put(wb[1].rows,ref,12+i));Object.defineProperty(wb[1].rows,'formulaRefs',{value:new Set(p.companionFormulas)});for(let i=0;i<wb.length;i++)if(i!==1)Object.defineProperty(wb[i].rows,'formulaRefs',{value:new Set()});for(const anchor of api.anchors[id])put(wb[anchor.sheet].rows,anchor.ref,anchor.aliases[0]);put(wb[0].rows,'A1','PRIVATE_PERSONAL_VALUE');return wb;}
for(const id of ['layout-21','layout-8']){
 test(`Round224 ${id} exact bilingual six labels remain accepted`,()=>{const wb=fixture(id),p=api.profiles[id];p.refs.forEach((ref,i)=>put(wb[1].rows,ref,`${labels[i]} (${['STR','DEX','CON','INT','WIS','CHA'][i]})`));assert.deepEqual(api.read(wb).fields.map(x=>x.status),Array(6).fill('label-match'));});
 test(`Round224 ${id} near-match and private note reject before numeric candidates`,()=>{for(const raw of ['力量：PRIVATE_PERSONAL_VALUE','PRIVATE_PERSONAL_VALUE力量','力量(STR)PRIVATE_PERSONAL_VALUE','力量123','力量\n某人的资料']){const wb=fixture(id);put(wb[1].rows,api.profiles[id].refs[0],raw);assert.throws(()=>api.read(wb),/标签或公式结构/);}});
 test(`Round224 ${id} swapped ability labels and calculated anchors reject`,()=>{let wb=fixture(id);put(wb[1].rows,api.profiles[id].refs[0],labels[1]);assert.throws(()=>api.read(wb),/标签或公式结构/);wb=fixture(id);wb[1].rows.formulaRefs.add(api.profiles[id].refs[0]);assert.throws(()=>api.read(wb),/标签或公式结构/);});
 test(`Round224 ${id} successful model and HTML contain neither private text nor new import control`,()=>{const wb=fixture(id),m=api.read(wb),s=JSON.stringify(m)+api.render(m,true,true);assert.ok(m.candidates.length===6&&m.sourceOutline.length===7);assert.equal(m.identityCombatImport,false);assert.doesNotMatch(s,/PRIVATE_PERSONAL_VALUE|PRIVATE_SHEET_SHOULD_NOT_RENDER|data-pc-dnd-identity-apply/);});
}
test('Round224 no substring based six-attribute signature or formula cache leak',()=>{const code=html.slice(a,b);assert.doesNotMatch(code,/observed\.includes\(label\)/);assert.match(code,/pcDndAbilityLabelMatches\(observed,i\)/);assert.match(code,/formula\.has\(ref\)/);assert.doesNotMatch(code,/sourceOutline.*raw:/);});
test('Round224 release caches and both CI remain synchronized and private files absent',()=>{const ver=html.match(/const APP_UI_VERSION = "([0-9.]+)"/)[1];const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');assert(sw.includes('v'+ver));assert.ok(html.includes('id="releaseNotesBox"><div class="version-log-item"><strong class="version-log-version">v'+ver));assert.ok((html.match(/class="version-log-version"/g)||[]).length>1);for(const f of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml']){const t=fs.readFileSync(path.join(root,'.github/workflows',f),'utf8');assert.match(t,/round224-dnd5-ability-anchor-guard\.test\.cjs/);assert.match(t,/round223-dnd5-private-diff-test\.py/);}assert.ok(!fs.readdirSync(root).some(x=>/\.xlsx$|\.pdf$/i.test(x)));});
