'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const start=html.indexOf('const PC_INSANE_PREVIEW_FIELDS=Object.freeze(['),end=html.indexOf('/* Stage55 pure parser end */',start);
assert.ok(start>0&&end>start);
const {preview,compare}=new Function(html.slice(start,end)+'\nreturn {preview:pcInsaneExcelPreviewFromSheets,compare:pcInsaneComparePreviewSheets};')();
function mock(){const rows=Array.from({length:42},()=>[]),set=(ref,val)=>{const [,letters,number]=ref.match(/^([A-Z]+)(\d+)$/);let col=0;for(const c of letters)col=26*col+c.charCodeAt(0)-64;rows[+number-1][col-1]=val;};for(const [ref,val] of [['G1','特技表'],['H16','技能名'],['A20','名字'],['A21','年龄'],['D21','性别'],['A26','职业'],['D22','生命力'],['D23','正气度'],['D24','功绩点'],['E22',6],['E23',5],['H17','基本攻击'],['H20','战场移动'],['E32',0],['E34',0],['E36',0]])set(ref,val);Object.defineProperty(rows,'formulaRefs',{value:new Set()});return {sheets:[{name:'角色表',rows}],set,rows};}
test('Round202 synthetic filled card shows only actual coordinate differences',()=>{const b=mock(),f=mock();f.set('B20','合成测试角色');f.set('B21',21);f.set('E22',4);const r=compare(f.sheets,b.sheets);assert.equal(r.changedCount,3);assert.equal(r.clearedCount,0);assert.equal(r.unchangedCount,4);assert.deepEqual(r.rows.filter(x=>x.state==='changed').map(x=>x.ref),['B20','B21','E22']);assert.equal(r.editionId,'');});
test('Round202 matching default value cannot establish whether user entered it',()=>{const b=mock(),f=mock();f.set('E22',6);const r=compare(f.sheets,b.sheets);assert.equal(r.rows.find(x=>x.ref==='E22').state,'unchanged');assert.equal(r.changedCount,0);});
test('Round202 populated second role card cannot masquerade as blank baseline',()=>{const b=mock(),f=mock();b.set('B20','旧值');assert.throws(()=>compare(f.sheets,b.sheets),/空白卡的 B20/);});
test('Round202 formula cache never creates confirmed differences',()=>{const b=mock(),f=mock();f.set('B20','#NAME?');f.rows.formulaRefs.add('B20');const r=compare(f.sheets,b.sheets);assert.equal(r.changedCount,0);assert.equal(r.rows.find(x=>x.ref==='B20').state,'formula');});
test('Round202 mismatched baseline is rejected rather than compared',()=>{const b=mock(),f=mock();b.set('A20','其他卡');assert.throws(()=>compare(f.sheets,b.sheets),/联系制作者/);});
test('Round202 comparison is opt-in and read-only',()=>{assert.match(html,/data-pc-insane-compare-open>对照空白卡/);assert.match(html,/id="pcInsaneBaselineInput"/);const source=html.slice(html.indexOf("document.getElementById('pcInsaneBaselineInput')?.addEventListener"),html.indexOf("document.addEventListener('click',async event=>{",html.indexOf("document.getElementById('pcInsaneBaselineInput')?.addEventListener")));assert.match(source,/pcInsaneComparePreviewSheets/);assert.doesNotMatch(source,/savePc|localStorage|pcMediaPut|pcDraft\s*=|pcWorkbookPending\s*=/);});
