'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const a=html.indexOf('/* Stage67: D&D 5e LOCAL numeric candidates'),b=html.indexOf('async function pcDndStructurePreviewFile(',a);
assert.ok(a>0&&b>a,'Stage67 candidate reader exists');
function cell(sheet,ref){const m=/^([A-Z]+)(\d+)$/.exec(ref);let col=0;for(const c of m[1])col=col*26+c.charCodeAt(0)-64;return sheet?.rows?.[+m[2]-1]?.[col-1]??'';}
const api=new Function('pcInsaneSheetCell',html.slice(a,b)+'return {read:pcDndStructurePreviewFromSheets,html:pcDndStructurePreviewHTML,profiles:PC_DND_STRUCTURE_LAYOUTS};')(cell);
const keys=['力量','敏捷','体质','智力','感知','魅力'];
const put=(rows,ref,val)=>{const m=/^([A-Z]+)(\d+)$/.exec(ref);let n=0;for(const c of m[1])n=n*26+c.charCodeAt(0)-64;rows[+m[2]-1]??=[];rows[+m[2]-1][n-1]=val;};
function workbook(layout){const p=api.profiles[layout],rows=[];p.refs.forEach((ref,i)=>put(rows,ref,keys[i]));p.candidateRefs.forEach((ref,i)=>put(rows,ref,12+i));Object.defineProperty(rows,'formulaRefs',{value:new Set(p.companionFormulas)});put(rows,'B3','PRIVATE_NAME_NEVER_RENDER');return Array.from({length:p.sheetCount},(_,i)=>({name:'PRIVATE_SHEET_NEVER_RENDER',rows:i===1?rows:[]}));}
test('Round218 A is prefilled candidate rather than player-entered attribute',()=>{const m=api.read(workbook('layout-21'));assert.deepEqual(m.candidates.map(x=>x.ref),api.profiles['layout-21'].candidateRefs);assert.ok(m.candidates.every(x=>x.state==='prefilled-unverified'));assert.equal(m.editionInferred,false);});
test('Round218 B is a distinct layout with no matching blank baseline',()=>{const m=api.read(workbook('layout-8'));assert.deepEqual(m.candidates.map(x=>x.ref),api.profiles['layout-8'].candidateRefs);assert.ok(m.candidates.every(x=>x.state==='candidate-unverified'));assert.equal(m.readOnly,true);});
test('Round218 user values masked by default, explicit local reveal toggles numeric only',()=>{const m=api.read(workbook('layout-8'));let t=api.html(m);for(const x of ['12','13','14','15','16','17'])assert.doesNotMatch(t,new RegExp('>'+x+'<'));assert.match(t,/显示本机候选数字/);assert.match(t,/•••/);t=api.html(m,true);assert.match(t,/>12<|>13</);assert.match(t,/隐藏本机候选数字/);});
test('Round218 formulas and cached formula values cannot masquerade as input',()=>{const wb=workbook('layout-8');wb[1].rows.formulaRefs.add('E8');put(wb[1].rows,'E8',28);const x=api.read(wb).candidates[0];assert.equal(x.state,'formula');assert.equal(x.value,null);assert.doesNotMatch(api.html(api.read(wb),true),/>28</);});
test('Round218 errors, arbitrary text, empty, fraction and out-of-range number never render source',()=>{let wb=workbook('layout-8');for(const [i,x] of ['#NAME?','PRIVATE_LONG_NOTE','',2.5,100].entries())put(wb[1].rows,api.profiles['layout-8'].candidateRefs[i],x);let m=api.read(wb),t=api.html(m,true);assert.deepEqual(m.candidates.slice(0,5).map(c=>c.state),['error','unverified','empty','unverified','unverified']);assert.equal(t.includes('PRIVATE_LONG_NOTE'),false);assert.equal(t.includes('#NAME?'),false);});
test('Round218 lookalike sheet count and labels without formula signatures is rejected',()=>{const wb=workbook('layout-8');wb[1].rows.formulaRefs.delete('G8');assert.throws(()=>api.read(wb),/公式结构/);});
test('Round218 unknown labels are rejected before candidate values are exposed',()=>{const wb=workbook('layout-8');put(wb[1].rows,'C8','INVALID');assert.throws(()=>api.read(wb),/标签/);});
test('Round218 private filenames/sheet names/notes never enter HTML and old rules untouched',()=>{const m=api.read(workbook('layout-8'));for(const word of ['PRIVATE_NAME_NEVER_RENDER','PRIVATE_SHEET_NEVER_RENDER']){assert.equal(JSON.stringify(m).includes(word),false);assert.equal(api.html(m,true).includes(word),false);}assert.doesNotMatch(html.slice(a,html.indexOf('/* Stage55: Insane',a)),/saveState\(|pcWorkbookPut\(|ruleSheets\s*=/);});
test('Round218 stale-file and dismissal invalidation remain wired, source outline stays open on value toggle',()=>{assert.match(html,/token!==pcDndPreviewToken\|\|pcDraft!==target/);assert.match(html,/\+\+pcDndPreviewToken;pcDndPreviewState=null/);assert.match(html,/const outlineOpen=Boolean\(body\.querySelector\('\.pc-dnd-outline'\)\?\.open\)/);assert.match(html,/pcDndStructurePreviewHTML\(pcDndPreviewState,!wasShown,outlineOpen\)/);});
test('Round218 CI version, browser runner and no real workbook bytes',()=>{const version=html.match(/const APP_UI_VERSION = "([^"]+)"/)?.[1];assert.match(version,/^8\.1\.12\.\d+$/);assert.ok(html.includes(`<strong class="version-log-version">v${version}</strong>`));assert.ok(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes(version));for(const f of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml'])assert.match(fs.readFileSync(path.join(root,'.github/workflows',f),'utf8'),/round218-dnd5-ability-candidates\.test\.cjs/);assert.ok(!fs.readdirSync(root).some(x=>/\.xlsx$|\.pdf$/i.test(x)));});
