'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const start=html.indexOf('/* Stage68: manual transcription of numeric candidates'),end=html.indexOf('async function pcDndManualApplyFromPreview()',start);
assert.ok(start>0&&end>start,'Stage68 pure planner and undo available');
const labels=['力量','敏捷','体质','智力','感知','魅力'];
const profiles={'layout-21':{candidateRefs:['I12','I14','I16','I18','I20','I22']},'layout-8':{candidateRefs:['E8','E10','E12','E14','E16','E18']}};
function scope(pc){return pc?.ruleMeta?.systemId==='dnd'&&['5e-2014','5e-2024'].includes(pc?.ruleMeta?.editionId)?'dnd:'+pc.ruleMeta.editionId:'';}
function current(pc){return pc.ruleSheets?.[scope(pc)]||{traits:labels.map(label=>({label,value:''})),skills:[],resources:[]};}
function editable(pc){const key=scope(pc);pc.ruleSheets??={};if(!pc.ruleSheets[key])pc.ruleSheets[key]=structuredClone(current(pc));return pc.ruleSheets[key];}
const api=new Function('clone','pcRuleTemplateKey','pcRuleEditableData','pcRuleCurrentData','PC_DND_SIX_LABELS','PC_DND_STRUCTURE_LAYOUTS',html.slice(start,end)+'return {plan:pcDndManualDraftPlan,undo:pcDndManualUndoPlan};')(structuredClone,scope,editable,current,labels,profiles);
function pc(edition='5e-2014',confirmed=true){return {id:'SYNTHETIC_PC',ruleMeta:{systemId:'dnd',editionId:edition,confirmed},ruleSheets:{},occupation:'KEEP_UNRELATED'};}
function model(layout='layout-8'){return {layoutId:layout,fields:labels.map(label=>({label,status:'label-match'})),candidates:labels.map((label,i)=>({label,ref:profiles[layout].candidateRefs[i],state:layout==='layout-21'?'prefilled-unverified':'candidate-unverified',value:11+i}))};}
test('Round219 manual opt-in writes only explicitly selected attributes, no original workbook',()=>{const original=pc(),{next,review}=api.plan(original,model(),[0,3]);assert.equal(next.ruleSheets['dnd:5e-2014'].traits[0].value,'11');assert.equal(next.ruleSheets['dnd:5e-2014'].traits[3].value,'14');assert.equal(next.ruleSheets['dnd:5e-2014'].traits[1].value,'');assert.equal(original.ruleSheets['dnd:5e-2014'],undefined);assert.deepEqual(review.changes.map(x=>x.ref),['E8','E14']);assert.ok(!('blob' in review));});
test('Round219 A template values require same explicit confirmation, never classified as player entry',()=>{const m=model('layout-21'),x=api.plan(pc(),m,[2]);assert.equal(m.candidates[2].state,'prefilled-unverified');assert.equal(x.next.ruleSheets['dnd:5e-2014'].traits[2].value,'13');});
test('Round219 no edition, unconfirmed edition and wrong system rejected',()=>{assert.throws(()=>api.plan(pc('',true),model(),[0]),/版次/);assert.throws(()=>api.plan(pc('5e-2024',false),model(),[0]),/版次/);const p=pc();p.ruleMeta.systemId='coc';assert.throws(()=>api.plan(p,model(),[0]),/版次/);});
test('Round219 populated existing fields are never overwritten, including historical extension',()=>{const p=pc();p.ruleSheets['dnd:5e-2014']={traits:[{label:'力量',value:'19',future:{keep:true}}],skills:[],resources:[]};assert.throws(()=>api.plan(p,model(),[0]),/覆盖/);assert.equal(p.ruleSheets['dnd:5e-2014'].traits[0].value,'19');assert.equal(p.ruleSheets['dnd:5e-2014'].traits[0].future.keep,true);});
test('Round219 selected range, duplicate selection, formula/error/out of range rejected atomically',()=>{for(const chosen of [[],[0,0],[8],[-1]])assert.throws(()=>api.plan(pc(),model(),chosen));for(const value of [0,31,2.4,Infinity,null]){const m=model();m.candidates[0].value=value;assert.throws(()=>api.plan(pc(),m,[0]));}const m=model();m.candidates[0].state='formula';assert.throws(()=>api.plan(pc(),m,[0]));});
test('Round219 duplicate labels or fake refs/labels fail closed',()=>{const p=pc();p.ruleSheets['dnd:5e-2014']={traits:[{label:'力量',value:''},{label:'力量',value:''}],skills:[],resources:[]};assert.throws(()=>api.plan(p,model(),[0]),/重名/);const m=model();m.candidates[0].ref='A1';assert.throws(()=>api.plan(pc(),m,[0]),/来源/);});
test('Round219 undo restores imported fields and retains unrelated edits',()=>{const {next,review}=api.plan(pc(),model(),[0,1]);next.occupation='LATER_MANUAL';const restored=api.undo(next,review);assert.equal(restored.occupation,'LATER_MANUAL');assert.equal(restored.ruleSheets['dnd:5e-2014']?.traits[0]?.value??'','');assert.notEqual(restored.ruleSheets['dnd:5e-2024']?.traits[0]?.value,'11');});
test('Round219 undo rejects changed imported item or edition, no stale overwrite',()=>{let {next,review}=api.plan(pc(),model(),[0]);next.ruleSheets[review.scope].traits[0].value='20';assert.throws(()=>api.undo(next,review),/拒绝/);next.ruleMeta.editionId='5e-2024';assert.throws(()=>api.undo(next,review),/版次/);});
test('Round219 save review is tied to current draft fingerprint and commit state',()=>{assert.match(html,/if\(pcDndDraftImportReview\)\{/);assert.match(html,/review\.pcId!==String\(pcDraft\.id/);assert.match(html,/JSON\.stringify\(canonicalPcFromRuntime\(pcDraft\)\)!==fingerprint/);assert.match(html,/pcDndDraftImportReview\.saveCommitted=true/);assert.match(html,/pcDndDraftImportReview=null;pcRuleDeleteUndoUi\.clear/);});
test('Round219 UI requires independent attestation, six opt-in checkboxes and no automatic save',()=>{assert.match(html,/data-pc-dnd-attest/);assert.match(html,/data-pc-dnd-pick/);assert.match(html,/data-pc-dnd-manual-apply/);assert.match(html,/核对并填入未保存草稿/);assert.doesNotMatch(html.slice(start,end),/saveState\(|pcWorkbookPut\(/);});
test('Round219 real savePcEditor commits only chosen values and reloads; concurrent edit refuses commit',async()=>{
 const original={...pc(),ownerPlId:'self',name:'SYNTHETIC_PC_NAME'},plan=api.plan(original,model(),[0,2]);
 const saved={raw:null},alerts=[],confirmations=[];let saves=0,mutate=false;
 const s=html.indexOf('async function savePcEditor(){'),e=html.indexOf('\nasync function deletePcArchive(',s),vs=html.indexOf('async function pcExcelVerifySavedPc('),ve=html.indexOf('\n/* v8.1.11.84',vs);assert.ok(s>0&&e>s&&vs>0&&ve>vs);
 const ctx={clone:structuredClone,pcDraft:structuredClone(plan.next),pcInsaneDraftImportReview:null,pcDndDraftImportReview:structuredClone(plan.review),pcRuleTemplateKey:scope,
  pcMediaUploadBusy:false,pcWorkbookSaveBusy:false,editingPcId:original.id,pcWorkbookPending:null,pcExcelTemplateProfilePending:null,pcMediaDraftMeta:new Map(),pcEditorNewMediaIds:new Set(),pcEditorDeleteMediaIds:new Set(),pcRuleDeleteUndoUi:new Map(),pcs:[structuredClone(original)],runPlans:[],runRecords:[],settings:{pcExcelTemplateProfiles:[]},profiles:[{id:'self'}],localStorage:{getItem:()=>saved.raw},STORAGE_KEY:'synthetic-only',
  pcById:id=>ctx.pcs.find(x=>x.id===id),profileById:id=>id==='self'?{id}:null,profileNameById:()=> '我',pcValidateArchiveInput:()=>'',pcCandidatesByOwnerName:()=>[],normalizedEntityNameKey:x=>String(x).toLowerCase(),canonicalPcFromRuntime:x=>structuredClone(x),normalizePcArchive:x=>structuredClone(x),
  appNotice:message=>alerts.push(message),appConfirm:async message=>{confirmations.push(message);if(mutate)ctx.pcDraft.occupation='CONCURRENT_SYNTHETIC_EDIT';return true;},
  pcMediaCommitDraftMeta:async()=>[],pcMediaRollbackDraftMeta:async()=>true,pcMediaDelete:async()=>true,pcWorkbookGet:async()=>null,pcWorkbookPut:async()=>true,pcWorkbookDelete:async()=>true,
  saveState:()=>{saves++;saved.raw=JSON.stringify({data:{pcs:structuredClone(ctx.pcs)}});return true;},safeParseStoredJson:JSON.parse,pcCrc32:()=>0,
  syncPcNameAcrossRuns:()=>{},editorMainSaveFailed:()=>false,markEditorMainSaveFailure:()=>{},clearEditorMainSaveFailure:()=>{},renderPcEditor:()=>{},renderPcArchive:()=>{},renderRunPlans:()=>{},renderRunRecords:()=>{},renderProfiles:()=>{},showToast:()=>{},pcEditorBaseline:'before'};
 vm.createContext(ctx);vm.runInContext(html.slice(vs,ve),ctx);vm.runInContext(html.slice(s,e),ctx);
 assert.equal(await ctx.savePcEditor(),true);assert.equal(saves,1);assert.ok(confirmations.some(x=>x.includes('D&D 版次')));assert.equal(ctx.pcDndDraftImportReview,null);
 let reloaded=JSON.parse(saved.raw).data.pcs[0];assert.equal(reloaded.ruleSheets['dnd:5e-2014'].traits[0].value,'11');assert.equal(reloaded.ruleSheets['dnd:5e-2014'].traits[2].value,'13');assert.equal(reloaded.ruleSheets['dnd:5e-2014'].traits[1].value,'');assert.equal(reloaded.ruleSheets['dnd:5e-2024'],undefined);
 ctx.pcDraft=structuredClone(plan.next);ctx.pcDndDraftImportReview=structuredClone(plan.review);ctx.pcs=[structuredClone(original)];mutate=true;
 assert.equal(await ctx.savePcEditor(),false);assert.equal(saves,1);assert.ok(alerts.some(x=>x.includes('确认期间发生变化')));
});
test('Round219 pending manual import blocks switching D&D rule scope until resolved',()=>{assert.match(html,/if\(pcDndDraftImportReview\)\{e\.preventDefault\(\);appNotice\('当前 PC 有尚未保存的 D&D 属性录入/);assert.match(html,/请先处理本次 D&D 属性录入，再修改规则身份/);});
test('Round219 both CI paths and current UI/cache version in lockstep',()=>{const version=html.match(/const APP_UI_VERSION = "([^"]+)"/)?.[1];assert.ok(version&&fs.readFileSync(path.join(root,'sw.js'),'utf8').includes(version));for(const f of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml'])assert.match(fs.readFileSync(path.join(root,'.github/workflows',f),'utf8'),/round219-dnd5-manual-draft\.test\.cjs/);assert.ok(!fs.readdirSync(root).some(x=>/\.xlsx$|\.pdf$/i.test(x)));});
