'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const workflow=fs.readFileSync(path.join(__dirname,'../workflows/pl-browser-synthetic.yml'),'utf8');
function section(start,end){const a=html.indexOf(start);assert(a>=0,`missing ${start}`);const b=html.indexOf(end,a+start.length);assert(b>a,`missing ${end}`);return html.slice(a,b);}
function fake(){const calls={header:0,footer:0,panels:[],draws:[],canvas:0};const ctx={fillStyle:'',fillRect:()=>{},scale:()=>{},save:()=>{},restore:()=>{},fillText:()=>{},drawImage:(...a)=>calls.draws.push(a)};const doc={createElement(tag){assert.equal(tag,'canvas');calls.canvas++;return{width:0,height:0,getContext:()=>ctx};}};return{calls,ctx,doc};}
const surf=section('function createContinuousExportSurface(baseW,baseH,preferredScale=1.35){','function drawUnifiedExportHeader(ctx, w, theme,');
const entity=section('  function entityContinuousLongCanvas(kind,entity,state,pages){','  async function buildPcPages(pc,state){');
function entityRuntime(){const {calls,ctx,doc}=fake();const source={pcRuleIsCoc:()=>true,document:doc,theme:()=>({bg:'#fff'}),pcFullArchiveBlocks:()=>[{title:'角色资料',h:170,draw:()=>calls.panels.push('资料')},{title:'CoC7 数值',h:230,draw:()=>calls.panels.push('数值')},{title:'技能',h:130,draw:()=>calls.panels.push('技能')}],moduleCompleteBlocks:(_m,_s,continuous)=>{calls.continuous=continuous;return[{title:'模组资料',h:200,gapAfter:18,draw:()=>calls.panels.push('模组资料')},{title:'模组简介',h:480,gapAfter:16,draw:()=>calls.panels.push('简介')}]},pcStatusLabel:()=>'',pcTimelineRows:()=>[],entityPcSnapshots:()=>[],entityPcSnapshotHasData:()=>true,moduleEntities:()=>[],header:()=>{calls.header++;return 180;},panel:(_ctx,_x,y,_w,_h,_t,label)=>{calls.panels.push('panel:'+label);return y+58;},drawUnifiedExportFooter:()=>calls.footer++};vm.createContext(source);vm.runInContext(surf+entity+'\nthis.renderEntity=entityContinuousLongCanvas;this.surface=createContinuousExportSurface;',source);return{source,calls};}
test('Round128 PC complete archive is redrawn from its blocks, not sliced page canvases',()=>{const {source,calls}=entityRuntime();const originalPages=[{id:'archive',canvas:{width:2160,height:1800}},{id:'archive',canvas:{width:2160,height:1800}}];const out=source.renderEntity('pc',{name:'测试角色',skills:[]},{order:['archive'],selected:['archive'],density:'compact'},originalPages);assert.equal(calls.header,1);assert.equal(calls.footer,1);assert.equal(calls.draws.length,0);assert.deepEqual(calls.panels.filter(s=>!s.startsWith('panel:')),['资料','数值','技能']);assert.ok(out.height<3600,'continuous layout must not include two padded source canvases');});
test('Round128 module complete archive uses continuous block layout and one total header/footer',()=>{const {source,calls}=entityRuntime();source.renderEntity('module',{name:'测试模组'},{order:['complete'],selected:['complete'],showHistory:false},[{id:'complete',canvas:{width:2160,height:2000}},{id:'complete',canvas:{width:2160,height:1500}}]);assert.equal(calls.continuous,true);assert.equal(calls.header,1);assert.equal(calls.footer,1);assert.equal(calls.draws.length,0);assert.deepEqual(calls.panels.filter(s=>!s.startsWith('panel:')),['模组资料','简介']);});
test('Round128 long surface checks canvas limits before allocating and preserves text size floor',()=>{const {source,calls}=entityRuntime();assert.throws(()=>source.surface(1080,40000,1.35),/内容过长/);assert.equal(calls.canvas,0);const r=source.surface(1080,2000,1.35);assert.ok(r.canvas.width>=1450&&r.canvas.height>=2600);assert.equal(calls.canvas,1);});
test('Round128 stats calendar/timeline rows, annual halves, recap rows, organizer have semantic builders',()=>{for(const token of ['function buildStatsContinuousCanvas(state=statsExportState)','statsExportPageRows(layout).flat()','drawStatsStoryBlock(ctx,item.id,item.x,y','function buildPlannerYearContinuousCanvas(rawState=plannerYearShowcaseState)','drawPlannerCompleteCalendarPage(ctx,pad,y','function buildContinuousRecapCanvas()','drawRow(ctx,row,34,y','longCanvasBuilder:()=>buildStatsContinuousCanvas(statsExportState)','longCanvasBuilder:()=>buildPlannerYearContinuousCanvas(plannerYearShowcaseState)','longCanvasBuilder:()=>buildContinuousRecapCanvas()','longCanvasBuilder:()=> (hoOrganizerMode==='])assert.ok(html.includes(token),`missing semantic long-form route: ${token}`);assert.doesNotMatch(html,/function buildSectionedLongExportCanvas\(/);});
test('Round128 statistics draws split segments in original order with one header and one footer',()=>{
 const snippet=section('function buildStatsContinuousCanvas(state=statsExportState){','function buildStatsExportCanvases(state=statsExportState,{preview=false}={}){');
 const {calls,doc}=fake(),marks=[];
 const state={document:doc,statsExportState:{},statsExportLayout:()=>({rows:[{},{}],headerBottom:180,baseW:1600,gap:18,data:{}}),statsExportPageRows:()=>[[{row:{height:130,items:[{id:'calendar',x:34,w:1500,h:130,segment:{months:[1,2,3,4,5,6]}}]}},{row:{height:175,items:[{id:'calendar',x:34,w:1500,h:175,segment:{months:[7,8,9,10,11,12]}}]}}]],hoExportTheme:()=>({bg:'#fff'}),drawStatsExportHeader:()=>calls.header++,drawStatsStoryBlock:(_c,id,_x,y,_w,_h,_t,_d,segment)=>marks.push([id,y,segment.months[0]]),drawUnifiedExportFooter:()=>calls.footer++};
 vm.createContext(state);vm.runInContext(surf+snippet+'\nthis.run=buildStatsContinuousCanvas;',state);const canvas=state.run();assert.equal(calls.header,1);assert.equal(calls.footer,1);assert.equal(canvas.width,2160);assert.deepEqual(marks.map(x=>x[2]),[1,7]);assert.ok(marks[1][1]>marks[0][1]);
});
test('Round128 annual complete calendar draws both halves in one canvas, without second cover',()=>{
 const snippet=section('function buildPlannerYearContinuousCanvas(rawState=plannerYearShowcaseState){','function buildPlannerYearShowcaseCanvases(rawState=plannerYearShowcaseState,{preview=false}={}){');
 const {calls,doc}=fake(),halves=[];
 const state={document:doc,plannerYearShowcaseState:{mode:'complete'},normalizePlannerYearShowcaseState:x=>x,plannerYearShowcaseData:()=>({events:[{}],year:2026,summary:{sessions:20,days:15,modules:5,tables:10}}),hoExportTheme:()=>({bg:'#fff'}),plannerCompletePageMetrics:()=>({height:450}),drawPlannerCompleteCalendarPage:(_c,_x,y,_w,_t,_d,months)=>halves.push([y,months[0]]),drawUnifiedExportHeader:()=>calls.header++,drawUnifiedExportFooter:()=>calls.footer++};
 vm.createContext(state);vm.runInContext(surf+snippet+'\nthis.run=buildPlannerYearContinuousCanvas;',state);const out=state.run();assert.equal(calls.header,1);assert.equal(calls.footer,1);assert.deepEqual(halves.map(x=>x[1]),[1,7]);assert.ok(out.height>1300);
});
test('Round128 long export is presentation-only and retains paged/ZIP path and error fallback',()=>{assert.match(html,/function resolveUnifiedExportPayload\(pending,allowPreviewFallback=false\)/);assert.match(html,/if\(layout!=="long"\)return\{layout:"pages"/);assert.match(html,/if\(!allowPreviewFallback\)throw err/);assert.match(html,/longCanvasBuilder:typeof options\?\.longCanvasBuilder/);assert.match(html,/function exportPendingAsZip\(pending\)/);assert.match(workflow,/round128-continuous-export-semantic\.test\.cjs/);});
