'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const a=html.indexOf('/* Stage60 pure controlled-draft gate start.'),b=html.indexOf('/* Stage60 pure controlled-draft gate end */',a),c=html.indexOf('/* Stage61 specialty mapping preflight start.'),d=html.indexOf('let pcInsanePreviewSheets=null',c);
assert.ok(a>0&&b>a&&c>b&&d>c);
const source=html.slice(a,b)+html.slice(c,d);
const clone=x=>JSON.parse(JSON.stringify(x)),pcRuleCurrentData=p=>p.ruleSheets?.insane||{traits:[],skills:[],resources:[]},pcRuleEditableData=p=>(p.ruleSheets??={}).insane??=clone(pcRuleCurrentData(p)),pcInsaneSheetCell=(sheet,ref)=>sheet?.cells?.[ref]||'',escapeHTML=x=>String(x??'').replace(/[&<>"']/g,y=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[y]));
const api=new Function('clone','pcRuleCurrentData','pcRuleEditableData','pcInsaneSheetCell','escapeHTML',source+'\nreturn {check:pcInsaneAbilityPreflight,plan:pcInsaneAbilityBuildPlan,undo:pcInsaneDraftUndoPlan,html:pcInsaneAbilityDraftHTML,current:pcInsaneAbilityCurrent,itemCheck:pcInsaneItemPreflight,itemHtml:pcInsaneItemPreflightHTML};')(clone,pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell,escapeHTML);
const pc=(withSheet=true)=>{const p={id:'fictional',name:'虚构人物',ownerPlId:'self',ruleMeta:{systemId:'insane',editionId:'2013-original',confirmed:true},future:{keep:true}};if(withSheet)p.ruleSheets={insane:{traits:[{label:'生命力',value:'6',future:'keep'}],skills:[],resources:[{label:'旧能力',value:'自填效果',future:{keep:true}}],futureSection:{keep:true}}};return p;};
const row=(name,ref='H18',state='changed')=>({value:name,ref,state}),supp=(...rows)=>({comparison:true,groups:{abilities:rows}});
function apply(p,selected=['H18']){const beforeSheetExisted=Object.hasOwn(p.ruleSheets||{},'insane'),plan=api.plan(p,supp(row('新能力','H18'),row('另一能力','H19')),selected,true);return {plan,review:{pcId:p.id,editionId:p.ruleMeta.editionId,changes:clone(plan.changes),beforeSheetExisted,afterSheet:clone(plan.next.ruleSheets.insane),saveCommitted:false}};}
test('Round211 name-only, only selected sources, unknown fields and original rows remain',()=>{const p=pc(),original=clone(p),{plan}=apply(p);assert.deepEqual(p,original);assert.equal(plan.next.ruleSheets.insane.resources.length,2);assert.equal(plan.next.ruleSheets.insane.resources[0].future.keep,true);assert.equal(plan.next.ruleSheets.insane.futureSection.keep,true);assert.equal(plan.next.future.keep,true);assert.deepEqual(plan.next.ruleSheets.insane.resources[1],{label:'新能力',value:'待补充',detail:'',insaneSource:{format:'community-large-v2',inputRef:'H18',editionId:'2013-original',scope:'name-only'}});assert.ok(!JSON.stringify(plan.next).includes('P40'));});
test('Round211 requires exact rule edition and acknowledgment',()=>{const p=pc();p.ruleMeta.editionId='';assert.throws(()=>api.plan(p,supp(row('新能力')),['H18'],true),/规则版次/);p.ruleMeta.editionId='2025-revised';p.ruleMeta.confirmed=false;assert.throws(()=>api.plan(p,supp(row('新能力')),['H18'],true),/规则版次/);p.ruleMeta.confirmed=true;assert.throws(()=>api.plan(p,supp(row('新能力')),['H18'],false),/版次/);});
test('Round211 rejects canonical-name duplicates across sheet and existing PC',()=>{const p=pc();for(const data of [supp(row('STAR','H18'),row('ｓｔａｒ','H19')),supp(row('旧能力','H18')),supp(row('新能力','H18'),row('新能力','H19'))]){const result=api.check(data,p);assert.ok(result.some(x=>x.status!=='名称来源已核对'));assert.throws(()=>api.plan(p,data,['H18'],true),/唯一核对/);}assert.equal(p.ruleSheets.insane.resources.length,1);});
test('Round211 rejects formula, clears, truncated, invalid refs and controls',()=>{for(const r of [row('=formula','H18','formula'),row('清空','H18','cleared'),{...row('长字段','H18'),sourceTruncated:true},row('越界','P40'),row('bad\nname','H18'),row('字'.repeat(101),'H18')]){const result=api.check(supp(r),pc());assert.equal(result[0].status,'待核对');assert.throws(()=>api.plan(pc(),supp(r),[r.ref],true),/唯一核对/);}});
test('Round211 selection uniqueness and 40-resource cap',()=>{assert.throws(()=>api.plan(pc(),supp(row('新能力')),[],true),/请选择/);assert.throws(()=>api.plan(pc(),supp(row('新能力')),['H18','H18'],true),/不重复/);const p=pc();p.ruleSheets.insane.resources=Array.from({length:40},(_,i)=>({label:`旧${i}`,value:'手填'}));assert.throws(()=>api.plan(p,supp(row('新能力')),['H18'],true),/上限/);});
test('Round211 undo removes only exact unchanged imported row and preserves later edits',()=>{const {plan,review}=apply(pc(),['H18','H19']);plan.next.notes='后来单独填写';plan.next.ruleSheets.insane.resources.push({label:'后来手填',value:'手写'});const after=api.undo(plan.next,review).next;assert.deepEqual(after.ruleSheets.insane.resources.map(x=>x.label),['旧能力','后来手填']);assert.equal(after.notes,'后来单独填写');assert.equal(after.ruleSheets.insane.futureSection.keep,true);});
test('Round211 undo refuses modified imported row, already committed, or newly filled rule sheet',()=>{const {plan,review}=apply(pc());plan.next.ruleSheets.insane.resources[1].value='后来手填';assert.throws(()=>api.undo(plan.next,review),/已被修改/);const second=apply(pc());second.review.saveCommitted=true;assert.throws(()=>api.undo(second.plan.next,second.review),/保存状态/);const blank=pc(false),third=apply(blank);assert.ok(!Object.hasOwn(api.undo(third.plan.next,third.review).next.ruleSheets,'insane'));third.plan.next.ruleSheets.insane.resources.push({label:'后来新增',value:'x'});assert.throws(()=>api.undo(third.plan.next,third.review),/其他修改/);});
test('Round211 actual savePcEditor readback preserves source and blocks confirmation-time drift',async()=>{
 const start=html.indexOf('async function savePcEditor(){'),stop=html.indexOf('\nasync function deletePcArchive(',start),vstart=html.indexOf('async function pcExcelVerifySavedPc('),vstop=html.indexOf('\n/* v8.1.11.84',vstart);assert.ok(start>0&&stop>start&&vstart>0&&vstop>vstart);
 const original=pc(),imported=apply(original),stored={raw:null},ctx={clone,pcDraft:clone(imported.plan.next),pcDndDraftImportReview:null,pcInsaneDraftImportReview:clone(imported.review),pcMediaUploadBusy:false,pcWorkbookSaveBusy:false,editingPcId:original.id,pcWorkbookPending:null,pcExcelTemplateProfilePending:null,pcMediaDraftMeta:new Map(),pcEditorNewMediaIds:new Set(),pcEditorDeleteMediaIds:new Set(),pcRuleDeleteUndoUi:new Map(),pcs:[clone(original)],runPlans:[],runRecords:[],settings:{pcExcelTemplateProfiles:[]},profiles:[{id:'self'}],localStorage:{getItem:()=>stored.raw},STORAGE_KEY:'synthetic-only',pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell,escapeHTML,
 pcById:id=>ctx.pcs.find(x=>x.id===id),profileById:id=>id==='self'?{id}:null,profileNameById:()=> '我',pcValidateArchiveInput:()=>'',pcCandidatesByOwnerName:()=>[],normalizedEntityNameKey:x=>String(x).toLowerCase(),canonicalPcFromRuntime:x=>clone(x),normalizePcArchive:x=>clone(x),
 appNotice:msg=>ctx.alerts.push(msg),appConfirm:async()=>true,alerts:[],pcMediaCommitDraftMeta:async()=>[],pcMediaRollbackDraftMeta:async()=>true,pcMediaDelete:async()=>true,pcWorkbookGet:async()=>null,pcWorkbookPut:async()=>true,pcWorkbookDelete:async()=>true,
 saveState:()=>{ctx.calls++;stored.raw=JSON.stringify({data:{pcs:clone(ctx.pcs)}});return true;},calls:0,safeParseStoredJson:JSON.parse,pcCrc32:()=>0,syncPcNameAcrossRuns:()=>{},editorMainSaveFailed:()=>false,markEditorMainSaveFailure:()=>{},clearEditorMainSaveFailure:()=>{},renderPcEditor:()=>{},renderPcArchive:()=>{},renderRunPlans:()=>{},renderRunRecords:()=>{},renderProfiles:()=>{},showToast:()=>{},pcEditorBaseline:'before'};
 vm.createContext(ctx);vm.runInContext(source,ctx);vm.runInContext(html.slice(vstart,vstop),ctx);vm.runInContext(html.slice(start,stop),ctx);
 assert.equal(await ctx.savePcEditor(),true);assert.equal(ctx.calls,1);assert.equal(ctx.pcInsaneDraftImportReview,null);const saved=JSON.parse(stored.raw).data.pcs[0];assert.equal(saved.ruleSheets.insane.resources[1].insaneSource.inputRef,'H18');assert.equal(saved.ruleSheets.insane.resources[0].future.keep,true);assert.equal(saved.future.keep,true);assert.equal(saved.ruleSheets.insane.resources[1].value,'待补充');
 const next=apply(original);ctx.pcDraft=clone(next.plan.next);ctx.pcInsaneDraftImportReview=clone(next.review);ctx.pcs=[clone(original)];ctx.appConfirm=async()=>{ctx.pcDraft.ruleSheets.insane.resources[1].value='手动更改';return true;};assert.equal(await ctx.savePcEditor(),false);assert.equal(ctx.calls,1);assert.equal(ctx.pcs[0].ruleSheets.insane.resources.length,1);
});
test('Round211 actual PC rule normalization preserves the newly added source provenance and future fields',()=>{
 function fn(name){const start=html.indexOf(`function ${name}(`);assert.ok(start>0,name);const brace=html.indexOf('{',start);let level=0,quote='',escape=false,line=false,block=false;
  for(let i=brace;i<html.length;i++){const x=html[i],n=html[i+1];if(line){if(x==='\n')line=false;continue;}if(block){if(x==='*'&&n==='/'){block=false;i++;}continue;}if(quote){if(escape){escape=false;continue;}if(x==='\\'){escape=true;continue;}if(x===quote)quote='';continue;}if(x==='/'&&n==='/'){line=true;i++;continue;}if(x==='/'&&n==='*'){block=true;i++;continue;}if(x==='"'||x==="'"||x==='`'){quote=x;continue;}if(x==='{')level++;if(x==='}'&&--level===0)return html.slice(start,i+1);}throw Error('Unclosed '+name);
 }
 const context=vm.createContext({clone,PC_RULE_SHEET_TEMPLATES:Object.freeze({insane:{},'brp-generic':{},shinobigami:{}})});
 for(const name of ['pcPreserveUnknownJsonProps','normalizePcRuleData','normalizePcRuleSheets'])vm.runInContext(fn(name),context);
 const {plan}=apply(pc());const first=context.normalizePcRuleSheets(plan.next.ruleSheets),again=context.normalizePcRuleSheets(JSON.parse(JSON.stringify(first)));
 assert.equal(again.insane.resources[1].label,'新能力');assert.equal(again.insane.resources[1].insaneSource.inputRef,'H18');assert.equal(again.insane.resources[1].insaneSource.scope,'name-only');assert.equal(again.insane.resources[0].future.keep,true);assert.equal(again.insane.futureSection.keep,true);
});
test('Round211 UI escapes source, browser action and before-save guard installed',()=>{const str=api.html(api.check(supp(row('<svg onload=alert(1)>')),pc()));assert.match(str,/&lt;svg/);assert.doesNotMatch(str,/<svg onload/);assert.match(str,/data-pc-insane-ability-ack/);assert.match(str,/data-pc-insane-ability-ref/);assert.match(html,/data-pc-insane-ability-apply/);assert.match(html,/pcInsaneAbilityBuildPlan\(pcDraft,session\.specialtySupplement,refs,ack\)/);const saved=html.slice(html.indexOf('async function savePcEditor(){'),html.indexOf('async function deletePcArchive('));assert.match(saved,/pcInsaneAbilityCurrent\(pcDraft,row\)/);assert.match(saved,/confirmationFingerprint=JSON\.stringify\(canonicalPcFromRuntime\(pcDraft\)\)/);});
test('Round211 CI, version/cache consistency and raw-file exclusion',()=>{for(const n of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml'])assert.match(fs.readFileSync(path.join(root,'.github/workflows',n),'utf8'),/round211-insane-ability-controlled-draft\.test\.cjs/);const browserWorkflow=fs.readFileSync(path.join(root,'.github/workflows/pl-browser-synthetic.yml'),'utf8');assert.match(browserWorkflow,/round211-insane-ability-draft-browser\.py/);assert.match(browserWorkflow,/round211_browser\.outcome/);const version=html.match(/const APP_UI_VERSION = "([^"]+)"/)?.[1];assert.match(version||'',/^8\.1\.12\.\d+$/);assert.match(fs.readFileSync(path.join(root,'sw.js'),'utf8'),new RegExp(version.replace(/\./g,'\\.')));for(const n of ['inSANe大判空白卡V2.0数据（自动卡）.xlsx','【新ins】角色卡汉化.pdf'])assert.equal(fs.existsSync(path.join(root,n)),false);});
