'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const a=html.indexOf('/* Stage60 pure controlled-draft gate start.'),b=html.indexOf('/* Stage60 pure controlled-draft gate end */',a),c=html.indexOf('/* Stage61 specialty mapping preflight start.'),d=html.indexOf('let pcInsanePreviewSheets=null',c);
assert.ok(a>0&&b>a&&c>b&&d>c);
const source=html.slice(a,b)+html.slice(c,d),clone=x=>JSON.parse(JSON.stringify(x));
const pcRuleCurrentData=p=>p.ruleSheets?.insane||{traits:[],skills:[],resources:[]};
const pcRuleEditableData=p=>(p.ruleSheets??={}).insane??={traits:[],skills:[],resources:[]};
const esc=x=>String(x??'').replace(/[&<>"']/g,y=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[y]));
const api=new Function('clone','pcRuleCurrentData','pcRuleEditableData','pcInsaneSheetCell','escapeHTML',source+'\nreturn {build:pcInsaneCombinedBuildPlan,undo:pcInsaneDraftUndoPlan,html:pcInsaneCombinedDraftHTML};')(clone,pcRuleCurrentData,pcRuleEditableData,()=>'',esc);
const pc=()=>({id:'synthetic',name:'旧名',age:'20',ruleMeta:{systemId:'insane',editionId:'2013-original',confirmed:true},ruleSheets:{insane:{traits:[],skills:[],resources:[],futureSection:{keep:'yes'}}},notes:'手写备注'});
function session(p){return {pcId:p.id,rows:[{key:'name',label:'姓名',ref:'B20',target:'name',source:'新名',current:'旧名',targetExists:true,editionId:'2013-original',pcId:p.id,eligible:true,reason:''}],specialtySupplement:{comparison:true,groups:{specialties:[{ref:'B29',value:'察觉',state:'changed',match:{domain:1,row:2,ref:'I2'}}],abilities:[{ref:'H18',value:'逃生',state:'changed'}],items:[{ref:'E32',label:'药瓶',value:'2',state:'changed'}]}}};}
const chosen=()=>({basic:['B20'],specialty:['B29'],ability:['H18'],item:['E32']});
test('Round216 four groups apply atomically, only 4 intended records and no original mutation',()=>{const p=pc(),old=clone(p),result=api.build(p,session(p),chosen(),true);assert.deepEqual(p,old);assert.equal(result.changes.length,4);assert.equal(result.next.name,'新名');const s=result.next.ruleSheets.insane;assert.equal(s.skills[0].label,'察觉');assert.equal(s.resources[0].label,'逃生');assert.equal(s.resources[1].label,'道具 · 药瓶');assert.equal(s.resources[1].value,'2');assert.equal(s.futureSection.keep,'yes');assert.equal(JSON.stringify(result.next).includes('sourceWorkbook'),false);});
test('Round216 one receipt undoes all four while preserving unrelated later user edit',()=>{const p=pc(),plan=api.build(p,session(p),chosen(),true);const review={pcId:p.id,editionId:p.ruleMeta.editionId,changes:clone(plan.changes),beforeSheetExisted:true,afterSheet:clone(plan.next.ruleSheets.insane),saveCommitted:false};plan.next.notes='撤销前继续编辑的备注';const undone=api.undo(plan.next,review).next;assert.equal(undone.name,'旧名');assert.equal(undone.notes,'撤销前继续编辑的备注');assert.deepEqual(undone.ruleSheets.insane.skills,[]);assert.deepEqual(undone.ruleSheets.insane.resources,[]);assert.equal(undone.ruleSheets.insane.futureSection.keep,'yes');});
test('Round216 later resource capacity failure leaves source PC untouched',()=>{const p=pc(),snapshot=clone(p);p.ruleSheets.insane.resources=Array.from({length:39},(_,i)=>({label:'已有'+i,value:''}));const before=clone(p);assert.throws(()=>api.build(p,session(p),chosen(),true),/40 项保存上限/);assert.deepEqual(p,before);assert.equal(snapshot.name,'旧名');});
test('Round216 duplicate refs and unacknowledged edition refuse the entire selection',()=>{const p=pc(),s=session(p);assert.throws(()=>api.build(p,s,{...chosen(),ability:['H18','H18']},true),/重复/);assert.throws(()=>api.build(p,s,chosen(),false),/版次/);assert.throws(()=>api.build(p,s,{basic:[],specialty:[],ability:[],item:[]},true),/至少一项/);assert.equal(p.name,'旧名');});
test('Round216 legacy separate buttons coexist and integrated control is real',()=>{assert.match(api.html(),/data-pc-insane-combined-apply/);assert.match(html,/pcInsaneDraftReviewHTML\(candidates\)\+pcInsaneCombinedDraftHTML\(\)/);assert.match(html,/const final=pcInsaneCombinedBuildPlan\(pcDraft,session,chosen,ack\)/);assert.match(html,/pcInsaneDraftImportReview=\{pcId:String\(pcDraft.id\|\|''\),editionId:String\(pcDraft.ruleMeta\?\.editionId\|\|''\),changes:final.changes/);for(const text of ['data-pc-insane-specialty-apply','data-pc-insane-ability-apply','data-pc-insane-item-apply'])assert.ok(html.includes(text));});
test('Round216 version, public-source isolation, and both CI contracts',()=>{const version=html.match(/const APP_UI_VERSION = "([^"]+)"/)?.[1];assert.match(version,/^8\.1\.12\.\d+$/);assert.ok(fs.readFileSync(path.join(root,'sw.js'),'utf8').includes(version));for(const n of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml'])assert.match(fs.readFileSync(path.join(root,'.github/workflows',n),'utf8'),/round216-insane-batch-review\.test\.cjs/);for(const n of ['inSANe大判空白卡V2.0数据（自动卡）.xlsx','【新ins】角色卡汉化.pdf'])assert.equal(fs.existsSync(path.join(root,n)),false);});
test('Round216 production PC save, readback and reopening preserve all four imports',async()=>{
 const original={...pc(),ownerPlId:'self'},combined=api.build(original,session(original),chosen(),true),stored={raw:null};
 const review={pcId:original.id,editionId:original.ruleMeta.editionId,changes:clone(combined.changes),beforeSheetExisted:true,afterSheet:clone(combined.next.ruleSheets.insane),saveCommitted:false};
 const s=html.indexOf('async function savePcEditor(){'),e=html.indexOf('\nasync function deletePcArchive(',s),vs=html.indexOf('async function pcExcelVerifySavedPc('),ve=html.indexOf('\n/* v8.1.11.84',vs);
 assert.ok(s>0&&e>s&&vs>0&&ve>vs);
 const ctx={clone,pcDraft:clone(combined.next),pcDndDraftImportReview:null,pcInsaneDraftImportReview:clone(review),pcMediaUploadBusy:false,pcWorkbookSaveBusy:false,editingPcId:original.id,pcWorkbookPending:null,pcExcelTemplateProfilePending:null,pcMediaDraftMeta:new Map(),pcEditorNewMediaIds:new Set(),pcEditorDeleteMediaIds:new Set(),pcRuleDeleteUndoUi:new Map(),pcs:[clone(original)],runPlans:[],runRecords:[],settings:{pcExcelTemplateProfiles:[]},profiles:[{id:'self'}],localStorage:{getItem:()=>stored.raw},STORAGE_KEY:'synthetic-only',pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell:()=>'',escapeHTML:esc,
 pcById:id=>ctx.pcs.find(x=>x.id===id),profileById:id=>id==='self'?{id}:null,profileNameById:()=> '我',pcValidateArchiveInput:()=>'',pcCandidatesByOwnerName:()=>[],normalizedEntityNameKey:x=>String(x).toLowerCase(),canonicalPcFromRuntime:x=>clone(x),normalizePcArchive:x=>clone(x),
 appNotice:msg=>ctx.alerts.push(msg),appConfirm:async()=>true,alerts:[],pcMediaCommitDraftMeta:async()=>[],pcMediaRollbackDraftMeta:async()=>true,pcMediaDelete:async()=>true,pcWorkbookGet:async()=>null,pcWorkbookPut:async()=>true,pcWorkbookDelete:async()=>true,saveState:()=>{stored.raw=JSON.stringify({data:{pcs:clone(ctx.pcs)}});return true;},safeParseStoredJson:JSON.parse,pcCrc32:()=>0,syncPcNameAcrossRuns:()=>{},editorMainSaveFailed:()=>false,markEditorMainSaveFailure:()=>{},clearEditorMainSaveFailure:()=>{},renderPcEditor:()=>{},renderPcArchive:()=>{},renderRunPlans:()=>{},renderRunRecords:()=>{},renderProfiles:()=>{},showToast:()=>{},pcEditorBaseline:'before'};
 vm.createContext(ctx);vm.runInContext(source,ctx);vm.runInContext(html.slice(vs,ve),ctx);vm.runInContext(html.slice(s,e),ctx);
 assert.equal(await ctx.savePcEditor(),true);assert.equal(ctx.alerts.length,0);assert.equal(ctx.pcInsaneDraftImportReview,null);
 const reloaded=JSON.parse(stored.raw).data.pcs[0];assert.equal(reloaded.name,'新名');assert.equal(reloaded.ruleSheets.insane.skills[0].insaneSource.inputRef,'B29');assert.equal(reloaded.ruleSheets.insane.resources[0].insaneSource.inputRef,'H18');assert.equal(reloaded.ruleSheets.insane.resources[1].value,'2');assert.equal(reloaded.ruleSheets.insane.futureSection.keep,'yes');
 ctx.pcs=clone(JSON.parse(stored.raw).data.pcs);assert.deepEqual(ctx.pcs[0],reloaded);
});
