'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const a=html.indexOf('/* Stage60 pure controlled-draft gate start.'),b=html.indexOf('/* Stage60 pure controlled-draft gate end */',a),c=html.indexOf('/* Stage61 specialty mapping preflight start.'),d=html.indexOf('let pcInsanePreviewSheets=null',c);
assert.ok(a>0&&b>a&&c>b&&d>c);
const source=html.slice(a,b)+html.slice(c,d),clone=x=>JSON.parse(JSON.stringify(x));
const pcRuleCurrentData=p=>p.ruleSheets?.insane||{traits:[],skills:[],resources:[]};
const pcRuleEditableData=p=>(p.ruleSheets??={}).insane??=clone(pcRuleCurrentData(p));
const pcInsaneSheetCell=(s,r)=>s.cells?.[r]||'';
const escapeHTML=x=>String(x??'').replace(/[&<>"']/g,y=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[y]));
const api=new Function('clone','pcRuleCurrentData','pcRuleEditableData','pcInsaneSheetCell','escapeHTML',source+'\nreturn {check:pcInsaneItemPreflight,plan:pcInsaneItemBuildPlan,undo:pcInsaneDraftUndoPlan,current:pcInsaneItemCurrent,html:pcInsaneItemDraftHTML};')(clone,pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell,escapeHTML);
const pc=(withSheet=true)=>{const p={id:'fictional',name:'虚构角色',ownerPlId:'self',ruleMeta:{systemId:'insane',editionId:'2013-original',confirmed:true},future:{keep:true}};if(withSheet)p.ruleSheets={insane:{traits:[{label:'生命力',value:'6',future:'keep'}],skills:[],resources:[{label:'旧能力',value:'手写',future:{keep:true}}],futureSection:{keep:true}}};return p;};
const r=(label,value,ref='E32',state='changed')=>({ref,label,value,state,usage:'使用',usageRef:'D32'});
const supp=(...rows)=>({comparison:true,groups:{items:rows}});
const rows=()=>supp(r('镇痛剂','2'),r('武器','1','E34'),r('护身符','0','E36'));
function apply(p,refs=['E32']){const beforeSheetExisted=Object.hasOwn(p.ruleSheets||{},'insane'),plan=api.plan(p,rows(),refs,true);return {plan,review:{pcId:p.id,editionId:p.ruleMeta.editionId,changes:clone(plan.changes),beforeSheetExisted,afterSheet:clone(plan.next.ruleSheets.insane),saveCommitted:false}};}
test('Round213 selective count-only, source provenance, future data, and original remain',()=>{const p=pc(),old=clone(p),{plan}=apply(p);assert.deepEqual(p,old);const resources=plan.next.ruleSheets.insane.resources;assert.equal(resources.length,2);assert.deepEqual(resources[1],{label:'道具 · 镇痛剂',value:'2',detail:'',insaneSource:{format:'community-large-v2',inputRef:'E32',labelRef:'B32',editionId:'2013-original',scope:'count-only'}});assert.equal(resources[0].future.keep,true);assert.equal(plan.next.future.keep,true);assert.equal(plan.next.ruleSheets.insane.futureSection.keep,true);assert.equal(JSON.stringify(plan.next).includes('D32'),false);});
test('Round213 rejects zero, default, formulas, whitespace and duplicate labels',()=>{const p=pc();for(const data of [supp(r('护身符','0','E36')),supp(r('武器','1','E34','unchanged')),supp(r('武器','1','E34','formula')),supp({...r('武器','1','E34'),whitespaceOnly:true}),supp(r('武器','1','E34'),r('武器','2','E36')),supp({...r('武器','1','E34'),labelSourceTruncated:true})]){assert.ok(api.check(data,p).every(x=>x.status!=='数量来源已核对'));assert.throws(()=>api.plan(p,data,[data.groups.items[0].ref],true),/唯一核对/);}});
test('Round213 acknowledges edition and never overwrites existing item',()=>{const p=pc();p.ruleMeta.confirmed=false;assert.throws(()=>api.plan(p,rows(),['E32'],true),/版次/);p.ruleMeta.confirmed=true;assert.throws(()=>api.plan(p,rows(),['E32'],false),/版次/);p.ruleSheets.insane.resources.push({label:'道具 · 镇痛剂',value:'9',detail:'手写'});assert.ok(api.check(rows(),p)[0].status!=='数量来源已核对');assert.throws(()=>api.plan(p,rows(),['E32'],true),/唯一核对/);assert.equal(p.ruleSheets.insane.resources.at(-1).value,'9');});
test('Round213 cannot exceed resource capacity or repeat source',()=>{const p=pc();assert.throws(()=>api.plan(p,rows(),['E32','E32'],true),/不重复/);assert.throws(()=>api.plan(p,rows(),[],true),/请选择/);p.ruleSheets.insane.resources=Array.from({length:40},(_,i)=>({label:'旧'+i,value:'x'}));assert.throws(()=>api.plan(p,rows(),['E32'],true),/上限/);});
test('Round213 field-scoped undo and refusal after manual change',()=>{const {plan,review}=apply(pc(),['E32','E34']);plan.next.notes='后来修改';plan.next.ruleSheets.insane.resources.push({label:'新能力',value:'手写'});const after=api.undo(plan.next,review).next;assert.deepEqual(after.ruleSheets.insane.resources.map(x=>x.label),['旧能力','新能力']);assert.equal(after.notes,'后来修改');const second=apply(pc());second.plan.next.ruleSheets.insane.resources[1].value='3';assert.throws(()=>api.undo(second.plan.next,second.review),/已被修改/);second.review.saveCommitted=true;assert.throws(()=>api.undo(second.plan.next,second.review),/保存状态/);});
test('Round213 new rule sheet undo is safe and does not delete other user work',()=>{const p=pc(false),{plan,review}=apply(p);assert.ok(!Object.hasOwn(api.undo(plan.next,review).next.ruleSheets,'insane'));plan.next.ruleSheets.insane.resources.push({label:'手写',value:'新'});assert.throws(()=>api.undo(plan.next,review),/其他修改/);});
test('Round213 actual production savePcEditor readback and post-confirmation drift protection',async()=>{const original=pc(),{plan,review}=apply(original),stored={raw:null},s=html.indexOf('async function savePcEditor(){'),e=html.indexOf('\nasync function deletePcArchive(',s),vs=html.indexOf('async function pcExcelVerifySavedPc('),ve=html.indexOf('\n/* v8.1.11.84',vs);assert.ok(s>0&&e>s&&vs>0&&ve>vs);let calls=0;
 const ctx={clone,pcDraft:clone(plan.next),pcDndDraftImportReview:null,pcInsaneDraftImportReview:clone(review),pcMediaUploadBusy:false,pcWorkbookSaveBusy:false,editingPcId:original.id,pcWorkbookPending:null,pcExcelTemplateProfilePending:null,pcMediaDraftMeta:new Map(),pcEditorNewMediaIds:new Set(),pcEditorDeleteMediaIds:new Set(),pcRuleDeleteUndoUi:new Map(),pcs:[clone(original)],runPlans:[],runRecords:[],settings:{pcExcelTemplateProfiles:[]},profiles:[{id:'self'}],localStorage:{getItem:()=>stored.raw},STORAGE_KEY:'synthetic-only',pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell,escapeHTML,
 pcById:id=>ctx.pcs.find(x=>x.id===id),profileById:id=>id==='self'?{id}:null,profileNameById:()=> '我',pcValidateArchiveInput:()=>'',pcCandidatesByOwnerName:()=>[],normalizedEntityNameKey:x=>String(x).toLowerCase(),canonicalPcFromRuntime:x=>clone(x),normalizePcArchive:x=>clone(x),
 appNotice:msg=>ctx.alerts.push(msg),appConfirm:async()=>true,alerts:[],pcMediaCommitDraftMeta:async()=>[],pcMediaRollbackDraftMeta:async()=>true,pcMediaDelete:async()=>true,pcWorkbookGet:async()=>null,pcWorkbookPut:async()=>true,pcWorkbookDelete:async()=>true,saveState:()=>{calls++;stored.raw=JSON.stringify({data:{pcs:clone(ctx.pcs)}});return true;},safeParseStoredJson:JSON.parse,pcCrc32:()=>0,syncPcNameAcrossRuns:()=>{},editorMainSaveFailed:()=>false,markEditorMainSaveFailure:()=>{},clearEditorMainSaveFailure:()=>{},renderPcEditor:()=>{},renderPcArchive:()=>{},renderRunPlans:()=>{},renderRunRecords:()=>{},renderProfiles:()=>{},showToast:()=>{},pcEditorBaseline:'before'};
 vm.createContext(ctx);vm.runInContext(source,ctx);vm.runInContext(html.slice(vs,ve),ctx);vm.runInContext(html.slice(s,e),ctx);assert.equal(await ctx.savePcEditor(),true);assert.equal(calls,1);const saved=JSON.parse(stored.raw).data.pcs[0];assert.equal(saved.ruleSheets.insane.resources[1].value,'2');assert.equal(saved.ruleSheets.insane.resources[1].insaneSource.scope,'count-only');assert.equal(saved.ruleSheets.insane.resources[0].future.keep,true);assert.equal(ctx.pcInsaneDraftImportReview,null);
 ctx.pcs=clone(JSON.parse(stored.raw).data.pcs);assert.equal(ctx.pcs[0].ruleSheets.insane.resources[1].value,'2');
 const retry=apply(original);ctx.pcDraft=clone(retry.plan.next);ctx.pcInsaneDraftImportReview=clone(retry.review);ctx.pcs=[clone(original)];ctx.appConfirm=async()=>{ctx.pcDraft.ruleSheets.insane.resources[1].value='9';return true;};assert.equal(await ctx.savePcEditor(),false);assert.equal(calls,1);assert.equal(ctx.pcs[0].ruleSheets.insane.resources.length,1);
});
test('Round213 HTML and workflow contract; raw references never shipped',()=>{const out=api.html(api.check(supp(r('<img src=x>','2')),pc()));assert.match(out,/&lt;img/);assert.doesNotMatch(out,/<img src/);assert.match(out,/data-pc-insane-item-ack/);assert.match(html,/data-pc-insane-item-apply/);for(const n of ['pl-browser-synthetic.yml','pl-native-restore-gate.yml'])assert.match(fs.readFileSync(path.join(root,'.github/workflows',n),'utf8'),/round213-insane-item-controlled-draft\.test\.cjs/);assert.match(html,/pcInsaneItemCurrent\(pcDraft,row\)/);for(const n of ['inSANe大判空白卡V2.0数据（自动卡）.xlsx','【新ins】角色卡汉化.pdf'])assert.equal(fs.existsSync(path.join(root,n)),false);});
