'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const start=html.indexOf('/* Stage60 pure controlled-draft gate start.'),end=html.indexOf('/* Stage60 pure controlled-draft gate end */',start);
assert.ok(start>0&&end>start,'real production source section must exist');
const source=html.slice(start,end);
const clone=x=>JSON.parse(JSON.stringify(x));
const pcRuleCurrentData=p=>p.ruleSheets?.insane||{traits:[{label:'生命力',value:''},{label:'正气度',value:''}],skills:[],resources:[]};
const pcRuleEditableData=p=>(p.ruleSheets??={}).insane??=clone(pcRuleCurrentData(p));
const pcInsaneSheetCell=(sheet,ref)=>sheet.cells[ref]??'';
const api=new Function('clone','pcRuleCurrentData','pcRuleEditableData','pcInsaneSheetCell',source+'\nreturn {candidates:pcInsaneDraftCandidates,plan:pcInsaneDraftBuildPlan,undo:pcInsaneDraftUndoPlan};')(clone,pcRuleCurrentData,pcRuleEditableData,pcInsaneSheetCell);
const fields=[['name','B20','虚构人物'],['age','B21','29'],['gender','E21','女'],['occupation','B26','考古学家'],['life','E22','8'],['sanity','E23','7']];
function sample(withSheet=true){const p={id:'fictional-pc',ownerPlId:'self',name:'原人物',age:'19',gender:'女',occupation:'原职业',ruleMeta:{systemId:'insane',editionId:'2013-original'},future:{keep:true}};if(withSheet)p.ruleSheets={insane:{traits:[{label:'生命力',value:'6',future:{keep:true}},{label:'正气度',value:'5'}],skills:[{label:'旧特技',value:'旧内容'}],resources:[],futureSection:{keep:true}}};return p;}
function compared(){return {comparison:true,format:'insane-community-large-v2-readonly',rows:fields.map(([key,ref,value])=>({key,ref,value,state:'changed'}))};}
function sheets(){return [{name:'角色表',rows:{formulaRefs:new Set()},cells:Object.fromEntries(fields.map(x=>[x[1],x[2]]))}];}
function apply(p,refs){const beforeExists=Object.prototype.hasOwnProperty.call(p.ruleSheets||{},'insane'),plan=api.plan(p,api.candidates(compared(),sheets(),p),refs);return {after:plan.next,review:{pcId:p.id,editionId:p.ruleMeta.editionId,changes:plan.changes,beforeSheetExisted:beforeExists,afterSheet:clone(plan.next.ruleSheets?.insane||null),saveCommitted:false}};}
test('Round207 undo restores imported fields, preserving unrelated manual changes and future props',()=>{const p=sample(),before=clone(p),{after,review}=apply(p,['B20','E22']);after.notes='user wrote this later';const result=api.undo(after,review).next;assert.equal(result.name,before.name);assert.equal(result.ruleSheets.insane.traits[0].value,'6');assert.equal(result.notes,'user wrote this later');assert.deepEqual(result.ruleSheets.insane.traits[0].future,{keep:true});assert.deepEqual(result.ruleSheets.insane.futureSection,{keep:true});assert.deepEqual(p,before);});
test('Round207 does not undo manual edits to an imported field or changed rule edition',()=>{const {after,review}=apply(sample(),['B20','E22']);after.ruleSheets.insane.traits[0].value='9';assert.throws(()=>api.undo(after,review),/已被再次编辑/);assert.equal(after.name,'虚构人物');const {after:second,review:other}=apply(sample(),['B20']);second.ruleMeta.editionId='2025-revised';assert.throws(()=>api.undo(second,other),/版次/);});
test('Round207 reverting new rule sheet requires no unrelated changes and restores absence',()=>{const p=sample(false),{after,review}=apply(p,['E22']);assert.equal(Object.hasOwn(p,'ruleSheets'),false);assert.equal(after.ruleSheets.insane.traits[0].value,'8');const undo=api.undo(after,review).next;assert.equal(Object.hasOwn(undo.ruleSheets,'insane'),false);const changed=clone(after);changed.ruleSheets.insane.skills.push({label:'手动特技',value:'已填写'});assert.throws(()=>api.undo(changed,review),/其他修改/);});
test('Round207 independent ordinary PC field edits remain after undo; undo cannot apply twice',()=>{const {after,review}=apply(sample(),['B20']);after.occupation='改过的职业';const result=api.undo(after,review).next;assert.equal(result.occupation,'改过的职业');assert.equal(result.name,'原人物');assert.throws(()=>api.undo(result,review),/再次编辑/);});
test('Round207 refuses a saved or malformed import list, without changing any draft',()=>{const {after,review}=apply(sample(),['B20']);const before=clone(after);review.saveCommitted=true;assert.throws(()=>api.undo(after,review),/保存状态/);review.saveCommitted=false;review.changes.push({...review.changes[0]});assert.throws(()=>api.undo(after,review),/无效/);assert.deepEqual(after,before);});
test('Round207 actual save function checks freshness after async confirmation and verifies localStorage readback',async()=>{
 const begin=html.indexOf('async function savePcEditor(){'),stop=html.indexOf('\nasync function deletePcArchive(',begin);assert.ok(begin>0&&stop>begin);
 const saveCode=html.slice(begin,stop);const verifyBegin=html.indexOf('async function pcExcelVerifySavedPc('),verifyStop=html.indexOf('\n/* v8.1.11.84',verifyBegin);
 assert.ok(verifyStop>verifyBegin);
 const saved={value:null},alerts=[],confirmations=[];let saveCount=0,confirmMutate=false;
 const p=sample(),{after,review}=apply(p,['B20','E22']);
 const ctx={clone,pcDraft:clone(after),pcDndDraftImportReview:null,pcInsaneDraftImportReview:clone(review),pcMediaUploadBusy:false,pcWorkbookSaveBusy:false,editingPcId:p.id,pcWorkbookPending:null,pcExcelTemplateProfilePending:null,pcMediaDraftMeta:new Map(),pcEditorNewMediaIds:new Set(),pcEditorDeleteMediaIds:new Set(),pcRuleDeleteUndoUi:new Map(),pcs:[clone(p)],runPlans:[],runRecords:[],settings:{pcExcelTemplateProfiles:[]},profiles:[{id:'self'}],localStorage:{getItem:()=>saved.value},STORAGE_KEY:'fictional-test',
  pcById:id=>ctx.pcs.find(x=>x.id===id),profileById:id=>id==='self'?{id}:null,profileNameById:()=> '我',pcValidateArchiveInput:()=>'',pcCandidatesByOwnerName:()=>[],normalizedEntityNameKey:x=>String(x).toLowerCase(),canonicalPcFromRuntime:x=>clone(x),normalizePcArchive:x=>clone(x),
  appNotice:(message)=>alerts.push(message),appConfirm:async message=>{confirmations.push(message);if(confirmMutate)ctx.pcDraft.name='其他标签编辑';return true;},
  pcMediaCommitDraftMeta:async()=>[],pcMediaRollbackDraftMeta:async()=>true,pcMediaDelete:async()=>true,pcWorkbookGet:async()=>null,pcWorkbookPut:async()=>true,pcWorkbookDelete:async()=>true,
  saveState:()=>{saveCount++;saved.value=JSON.stringify({data:{pcs:clone(ctx.pcs)}});return true;},safeParseStoredJson:JSON.parse,pcCrc32:()=>0,
  syncPcNameAcrossRuns:()=>{},editorMainSaveFailed:()=>false,markEditorMainSaveFailure:()=>{},clearEditorMainSaveFailure:()=>{},renderPcEditor:()=>{},renderPcArchive:()=>{},renderRunPlans:()=>{},renderRunRecords:()=>{},renderProfiles:()=>{},showToast:()=>{},pcEditorBaseline:'old',pcExcelVerifySavedPc:null};
 vm.createContext(ctx);ctx.pcRuleCurrentData=pcRuleCurrentData;ctx.pcRuleEditableData=pcRuleEditableData;ctx.pcInsaneSheetCell=pcInsaneSheetCell;vm.runInContext(source,ctx);vm.runInContext(verifyBegin>=0?html.slice(verifyBegin,verifyStop):'',ctx);vm.runInContext(saveCode,ctx);
 assert.equal(await ctx.savePcEditor(),true);assert.equal(saveCount,1);assert.equal(ctx.pcDraft.name,'虚构人物');assert.equal(ctx.pcs[0].ruleSheets.insane.traits[0].value,'8');assert.deepEqual(JSON.parse(saved.value).data.pcs[0].future,{keep:true});assert.equal(ctx.pcInsaneDraftImportReview,null);
 const parsed=JSON.parse(saved.value);ctx.pcs=clone(parsed.data.pcs);ctx.pcDraft=clone(ctx.pcs[0]);assert.equal(ctx.pcDraft.name,'虚构人物');assert.equal(ctx.pcDraft.ruleSheets.insane.traits[0].value,'8');
 const again=apply(sample(),['B20']);ctx.pcDraft=clone(again.after);ctx.pcInsaneDraftImportReview=clone(again.review);ctx.pcs=[sample()];ctx.editingPcId=p.id;confirmMutate=true;
 assert.equal(await ctx.savePcEditor(),false);assert.equal(saveCount,1);assert.ok(alerts.some(x=>x.includes('确认期间发生变化')));assert.equal(ctx.pcs[0].name,'原人物');
});
test('Round207 a committed but unverified import is not submitted twice',()=>{const code=html.slice(html.indexOf('async function savePcEditor(){'),html.indexOf('async function deletePcArchive('));assert.match(code,/pcInsaneDraftImportReview\.saveCommitted\)\{appNotice/);assert.match(code,/勿重复覆盖/);});
test('Round207 UI exposes undo and on-save confirmation remains explicit',()=>{assert.match(html,/data-pc-insane-draft-undo/);assert.match(html,/pcInsaneDraftUndoPlan\(pcDraft,pcInsaneDraftImportReview\)/);assert.match(html,/confirmationFingerprint=JSON\.stringify\(canonicalPcFromRuntime\(pcDraft\)\)/);assert.match(html,/pcInsaneDraftImportReview\.saveCommitted=true/);});
test('Round207 CI and version/cache matches; raw Insane source files absent',()=>{const wf=fs.readFileSync(path.join(root,'.github/workflows/pl-browser-synthetic.yml'),'utf8'),native=fs.readFileSync(path.join(root,'.github/workflows/pl-native-restore-gate.yml'),'utf8');for(const t of [wf,native])assert.match(t,/round207-insane-undo-save-readback\.test\.cjs/);assert.match(html,/const APP_UI_VERSION = "8\.1\.12\.\d+"/);assert.match(fs.readFileSync(path.join(root,'sw.js'),'utf8'),new RegExp(html.match(/const APP_UI_VERSION = "([^"]+)"/)?.[1]||'__missing_version__'));for(const f of ['inSANe大判空白卡V2.0数据（自动卡）.xlsx','【新ins】角色卡汉化.pdf'])assert.equal(fs.existsSync(path.join(root,f)),false);});
